on:
  push: {branches: master}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: output-set
        uses: lukka/github-script@master
        with:
          script: ${{ github.workspace }}/__test__/script.js
          result-encoding: string
          input-value: output
      - run: |
          if [[ "${{steps.output-set.outputs.result}}" != "output" ]]; then
            exit 1
          fi
